version: "3.4"

services:
  api:
    ports:
      - "4000:4000"
    command: npm run dev
    volumes:
      - ./apps/api:/usr/app

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
